// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "The project convention requires the explicit form 'condition == false' instead of '!condition', because the leading negation operator is easy to overlook when reading a long condition", Scope = "module")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "Helper members are kept as instance members so they stay overridable and testable, and so that making a member static later is not a binary breaking change for derived processors", Scope = "module")]

[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "Entity mapping code repeats table and column names by design; extracting them into constants would separate the name from the mapping it belongs to", Scope = "namespace", Target = "~N:F1Server.Db.Entity")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "The observability check reports the same setting names in several branches; naming each one at the point where it is reported keeps the log messages readable", Scope = "member", Target = "~M:F1Server.Program.CheckObservability(System.IServiceProvider)")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "Migration code is generated by EF Core and must stay byte-identical to the generated output, so its repeated literals cannot be refactored", Scope = "namespace", Target = "~N:F1Server.Db.MySqlMigrations.Migrations")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "Migration code is generated by EF Core and must stay byte-identical to the generated output, so its repeated literals cannot be refactored", Scope = "namespace", Target = "~N:F1Server.Db.MsSqlMigrations.Migrations")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "Migration code is generated by EF Core and must stay byte-identical to the generated output, so its repeated literals cannot be refactored", Scope = "namespace", Target = "~N:F1Server.Db.PostgreSqlMigrations.Migrations")]

// S1244 is scoped to the two namespaces that compare raw packet floats on purpose. Telemetry
// floats arrive as exact bit patterns from the game and are compared against the sentinel value
// the game itself sends (typically 0), not against a computed result, so no tolerance applies.
// Everywhere else the rule stays active, because there a floating point equality really is a bug.
[assembly: SuppressMessage("Major Bug", "S1244:Floating point numbers should not be tested for equality", Justification = "Packet data classes compare unmodified telemetry floats against the sentinel values sent by the game, never against a computed result, so an epsilon comparison would be wrong here", Scope = "namespaceanddescendants", Target = "~N:F1Server.Core.Packets.Data")]
[assembly: SuppressMessage("Major Bug", "S1244:Floating point numbers should not be tested for equality", Justification = "Processors compare telemetry floats that were carried through unchanged from the packet to detect whether the game reported a new value, which requires an exact comparison", Scope = "namespaceanddescendants", Target = "~N:F1Server.Service.Processors")]

[assembly: SuppressMessage("Major Code Smell", "S6968:Actions that return a value should be annotated with ProducesResponseTypeAttribute containing the return type", Justification = "The response type is already carried by the action signature and is picked up from there for the generated API description; repeating it in an attribute would duplicate the signature without adding information", Scope = "module")]

[assembly: SuppressMessage("Maintainability", "S2094:Classes should not be empty", Justification = "Marker types such as ITelemetryClient are intentionally empty and exist only to identify and register implementations", Scope = "module")]

[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Migration code is generated by EF Core and must stay byte-identical to the generated output, so its inline arrays cannot be hoisted into static fields", Scope = "namespace", Target = "~N:F1Server.Db.MySqlMigrations.Migrations")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Migration code is generated by EF Core and must stay byte-identical to the generated output, so its inline arrays cannot be hoisted into static fields", Scope = "namespace", Target = "~N:F1Server.Db.MsSqlMigrations.Migrations")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Migration code is generated by EF Core and must stay byte-identical to the generated output, so its inline arrays cannot be hoisted into static fields", Scope = "namespace", Target = "~N:F1Server.Db.PostgreSqlMigrations.Migrations")]