<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\F1Server.Core\F1Server.Core.csproj" />
    <ProjectReference Include="..\F1Server.Shared\F1Server.Shared.csproj" />
  </ItemGroup>

</Project>
